# Generated by Django 3.2.12 on 2022-02-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('isbn_num', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('library_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryActivities',
            fields=[
                ('library_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CHECK_IN', 'CHECK_IN'), ('CHECK_OUT', 'CHECK_OUT')], default='CHECK_IN', max_length=10)),
                ('checked_out_at', models.DateTimeField(null=True)),
                ('checked_in_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUsers',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBooks',
            fields=[
                ('library_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.books')),
                ('last_library_activity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_activity', to='src.libraryactivities')),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.libraries')),
            ],
        ),
        migrations.AddField(
            model_name='libraryactivities',
            name='library_book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_book', to='src.librarybooks'),
        ),
        migrations.AddField(
            model_name='libraryactivities',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.libraryusers'),
        ),
    ]
